name: Repository Events
on:
  push:
    branches:
      - main
      - "feature/*" # matches feature/featA, feature/featB
      - "feature/**" # matches feature/featA, feature/featB feature/featA/featB
      - "!feature/featA" # Ignores feature/featA (ORDER MATTERS, PUT AT END)
    # branches-ignore:
    #   - development
    tags:
      - v1.* # matches v1.1, v1.2
      - "!v1.1.1" # Ignores v1.1.1
    # tags-ignore:
    #   - v1.*
    paths:
      - "**.js"


  pull_request:
    types: [opened, assigned, reopened, synchronize]
    branches:
      - main
    paths:
      - "**.js" # Will only run for changes on js files targeting main branch
  issues:
    types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Variables
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
      - name: Checkout Repository
        uses: actions/checkout@v3